name: teamsync_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.3

  # Firebase packages
  firebase_core: ^3.3.0 # Assicurati che questa versione sia compatibile con gli altri pacchetti
  firebase_auth: ^5.1.2 # Assicurati che questa versione sia compatibile con firebase_core
  cloud_firestore: ^5.1.0 # Utilizza una versione compatibile e disponibile
  firebase_storage: ^12.1.1 # Assicurati che questa versione sia compatibile con firebase_core
  intl: ^0.19.0
  logging: ^1.2.0

  # UUID package
  uuid: ^3.0.6 # Aggiungi questa dipendenza per generare UUID

  share_plus: ^8.0.0

  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/im_pagina_di_benvenuto1.png
    - assets/sfondo_pagina_di_benvenuto1.png
    - assets/im_pagina_di_benvenuto2.png
    - assets/sfondo_pagina_di_benvenuto2.png
    - assets/im_pagina_di_benvenuto3.png
    - assets/sfondo_pagina_di_benvenuto3.png
    - assets/im_pagina_di_benvenuto4.png
    - assets/sfondo_pagina_di_benvenuto_4.png
    - assets/im_pagina_di_benvenuto5.png
    - assets/sfondo_pagina_di_benvenuto5.png
    - assets/im_pagina_di_benvenuto6.png
    - assets/sfondo_pagina_di_benvenuto6.png
    - assets/user_icon.png
    - assets/icon.png
    - assets/background.png
    - assets/registrazione.png
    - assets/im_mailbox.png
    - assets/nessun_progetto___image.png
    - assets/logo_teamsync.png
