// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7nmU9b_OE23BqpCTJma2HrGl-pE5Rpc4',
    appId: '1:74749629811:android:20b0de42b13c8811afe106',
    messagingSenderId: '74749629811',
    projectId: 'teamsync-97a04',
    databaseURL: 'https://teamsync-97a04-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-97a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBggGbGRiWx2frBgT_EjhTaPzvvkYUJyM4',
    appId: '1:74749629811:ios:c55d93587c381297afe106',
    messagingSenderId: '74749629811',
    projectId: 'teamsync-97a04',
    databaseURL: 'https://teamsync-97a04-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-97a04.appspot.com',
    androidClientId: '74749629811-srl7te7chk4l8i305ne2mj9ur5i2m7rq.apps.googleusercontent.com',
    iosClientId: '74749629811-pkphrjkop0itdeu8hdrf072j2574h5vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamsyncFlutter',
  );

}